replicaCount: 1

image:
  api:
    repository: ghcr.io/mlops-project/api
    tag: 1.0.5
    pullPolicy: IfNotPresent
  mariadb:
    repository: mariadb
    tag: latest

nameOverride: "imdb-services"

serviceAccount:
  create: false
  name: default

service:
  api:
    type: NodePort
    targetPort: 80
    port: 80
    nodePort: 30120
  mariadb:
    type: ClusterIP
    targetPort: 3306
    port: 3306

secret:
  name: db-connection

env:
  secret:
    MYSQL_PORT: "3306"
    MYSQL_HOST: svc-mariadb
    MYSQL_DATABASE: imdb
    MYSQL_USER: my_user
    MYSQL_ROOT_PASSWORD: my_root_password
    MYSQL_PASSWORD: my_password
    AZURE_WEBSERVICE_URL: ""

nodeSelector:
  kubernetes.io/hostname: bruyneel-branco
