replicaCount: 1

image:
  api:
    repository: ghcr.io/mlops-project/api
    tag: 1.0.5
    pullPolicy: IfNotPresent
  mariadb:
    repository: mariadb
    tag: latest

nameOverride: "imdb-services"

serviceAccount:
  create: false
  name: default

service:
  api:
    type: ClusterIP
    targetPort: 80
    port: 80
  mariadb:
    type: ClusterIP
    targetPort: 3306
    port: 3306

secret:
  name: app-env-var-secret
env:
  normal:
    MYSQL_PORT: 3306
    MYSQL_HOST: mariadb
    MYSQL_DATABASE: imdb
  secret:
    MYSQL_USER: my_user
    MYSQL_ROOT_PASSWORD: my_root_password
    MYSQL_PASSWORD: my_password

nodeSelector:
  kubernetes.io/hostname: bruyneel-branco
