apiVersion: v1
kind: PersistentVolume
metadata:
  name: bruyneel-branco-imdb-db
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data/imdb
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bruyneel-branco
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
