apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bruyneel-branco-imdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: bruyneel-branco-imdb-db
