apiVersion: v1
kind: Service
metadata:
  name: svc-api
  labels:
{{ include "example.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
      protocol: TCP
      name: clusterIP
  selector:
    app.kubernetes.io/name: {{ include "example.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: api
