apiVersion: v1
kind: Service
metadata:
  name: svc-api
  labels:
{{ include "example.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
      nodePort: {{ .Values.service.api.nodePort }}
      protocol: TCP
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-bruyneel-branco-imdb-api
