apiVersion: v1
kind: Service
metadata:
  name: svc-mariadb
  labels:
{{ include "example.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.mariadb.type }}
  ports:
    - port: {{ .Values.service.mariadb.port }}
      targetPort: {{ .Values.service.mariadb.targetPort }}
      protocol: TCP
      name: clusterIP
  selector:
    app.kubernetes.io/name: {{ include "example.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: mariadb
